config/routes.rb
Rails.application.routes.draw do
	resources :events
	get "/welcome" => "welcome#index"
	root "events#index"
	#match ':controller(/:action(/:id(.:format)))', :via => :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
	belongs_to :event
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :attendees
	belongs_to :category, :optional => true
	has_one :location
	has_many :event_groupships
	has_many :groups, :through => :event_groupships
	validates_presence_of :name
end

app/models/event_groupship.rb
class EventGroupship < ApplicationRecord
	belongs_to :event
	belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :event_groupships
	has_many :events, :through => :event_groupships
end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :set_event, :only =>[:show, :edit, :update, :destroy]
	#GET /events/index
	#GET /events
	def index
		@events = Event.page(params[:page]).per(10)

		respond_to do |format|
			format.html
			format.json {
				render :json => @events.to_json
			}
		end

	end

	#GET /events/:id
	def show
		respond_to do |format|
			format.html
			format.json {
				render :json => {:id => @event.id, :name => @event.name, :description => @event.description}.to_json
			}
		end
	end

	#GET /events/new
	def new
		@event = Event.new
	end

	#POST /events
	def create
		@event = Event.new(event_params)
		if @event.save
			flash[:notice] = "新增成功"
			redirect_to events_path
		else
			render :action => :new
		end
	end

	#PATCH /events/:id/edit
	def edit
	end

	#PATCH /events/:id
	def update
		if @event.update(event_params)
			flash[:notice] = "更新成功"
			redirect_to event_path(@event)
		else 
			render :action => :edit
		end	
	end

	#DELETE /events/:id
	def destroy
		@event.destroy
		flash[:alert] = "删除成功"
		redirect_to events_path
	end

	private

	def set_event
  	@event = Event.find(params[:id])
	end

	def event_params
		params.require(:event).permit(:name, :description)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	#GET Action /welcome/index
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <ul>
	  <% @event.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
  </ul>
<% end %>
<div class="form-group">
	<%= f.label :name, "Name:"%>
	<%= f.text_field :name, :class => "form-control"%>
</div>
<div class="form-group">
	<%= f.label :description, "Description:" %>
	<%= f.text_area :description, :class => "form-control" %>
</div>

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event),:method => :patch do |f| %>
    <%= render :partial => 'form', :locals => {:f => f } %>

    <%= f.submit "Update" ,:class => "btn btn-primary"%>
<% end %>

app/views/events/index.html.erb
<h1>Events List</h1>
<table class="table table-bordered">
	<% @events.each do |e| %>
		<tr>
			<td>
				<%= e.name %>
			</td>
			<td>
			<%= link_to 'Show', event_path(e), :class => "btn btn-primary" %>
			
			<%= link_to 'Go Json', event_path(e,:format => :json) , :class => "btn btn-default"%>
			
			<%= link_to 'Edit', edit_event_path(e), :class => "btn btn-default" %>
			
			<%= link_to 'Delete', event_path(e), :method => :delete , :class => "btn btn-danger"%>
			</td>
		</tr>
	<% end %>
</table>
<%= link_to 'New', new_event_path,:class => "btn btn-primary"%>
<br/>
<%= paginate @events %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>

		<%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "Create",:class => "btn btn-primary" %>
<% end %>
  

app/views/events/show.html.erb
<h4>详细信息</h4>

<ul>
	<li>
		<%= @event.name %>
	</li>
	<li>
		<%= simple_format(@event.description) %>
	</li>
</ul>

<p><%= link_to 'Back to index', events_path,:class => "btn btn-primary" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events Application</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <% if flash[:notice].present? %>
            <div class="alert alert-success" role="alert">
              <%= flash[:notice]%>
            </div>
          <% end %>
          <% if flash[:alert].present? %>
            <div class="alert alert-danger" role="alert">
              <%= flash[:alert] %>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>That's My First Rails Projects</h1>
<h1>Hello World</h1>